version: '3.8'

services:
  kambit-mongodb:
    image: mongo:6
    container_name: kambit-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongo-data:/data/db
    networks:
      - kanban-network

volumes:
  mongo-data:

networks:
  kanban-network:
    driver: bridge
